language: python

matrix:
  include:
    - dist: bionic
      python: 3.7
    - os: osx
      osx_image: xcode10.2
      language: shell

script:
  - echo ${TRAVIS_PYTHON_VERSION}
  - python3 -m unittest test.py || python -m unittest test.py
